const Erros = {
    CNPJ_INVALIDO: "CNPJ_INVALIDO",
    CNPJ_IMCOMPELTO: "CNPJ_IMCOMPLETO",
    ID_INVALIDO: "ID_INVALIDO",
    PETSHOP_INVALIDO: "PETSHOP_IVALIDO",
    NOME_INVALIDO: "NOME_INVALIDO",
    NOME_INDEFINIDO: "NOME_INDEFINIDO"
    
} as const

export default Erros
