const Erros = {
    CNPJ_INVALIDO: "CNPJ_INVALIDO",
    CNPJ_IMCOMPELTO: "CNPJ_IMCOMPLETO",
    ID_INVALIDO: "ID_INVALIDO",
    PETSHOP_INVALIDO: "PETSHOP_IVALIDO",
    NOME_INVALIDO: "NOME_INVALIDO",
    NOME_INDEFINIDO: "NOME_INDEFINIDO",
    PETSHOP_JA_EXISTE: "PETSHOP_JA_EXISTE",
    PET_NAO_REGISTRADO: "PET_NAO_REGISTRADO",
    PETSHOP_NAO_EXISTE: "PETSHOP_NOA_EXISTE",
    CNPJ_NAO_EXISTE: "CNPJ_NAO_EXISTE",
    CNPJ_JA_EXISTE: "CNPJ_JA_EXISTE",
    PETS_NAO_ENCOTRADOS: "PETS_NAO_ENCONTRADOS",
    ID_INEXISTENTE:  "ID_INEXISTENTE"
    
} as const

export default Erros
